<a href="https://colab.research.google.com/github/AbdallaYoussef006/FlyRank-AI/blob/main/work/notebooks/w04_baseline_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-07 — Baseline Action Score and Top-20 Review

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

## Baseline Rule

Pages with many impressions but poor average position should be reviewed first because improving rankings on high-traffic pages can generate the largest increase in clicks.

### Reason Codes

HIGH_VOLUME_LOW_POSITION

HIGH_VOLUME

LOW_POSITION

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [ ]:
import pandas as pd
import os

queue = con.sql(f"""
SELECT
    content_hash_id,
    client_hash_id,
    SUM(gsc_impressions) AS impressions,
    AVG(gsc_sum_position) AS avg_position
FROM {TABLES['fact_daily']}
GROUP BY 1,2
""").df()

queue["score"] = (
    queue["impressions"]/1000 +
    queue["avg_position"]/10
)

queue["reason_code"] = "HIGH_VOLUME_LOW_POSITION"
queue["action"] = "SEO_REVIEW"

queue = queue.sort_values("score", ascending=False)

os.makedirs("work/outputs", exist_ok=True)

queue.to_csv(
    "work/outputs/baseline_action_score.csv",
    index=False
)

queue.head(20)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,content_hash_id,client_hash_id,impressions,avg_position,score,reason_code,action
160364,content_c60628276389acbb,client_23a62021009f63c4,286861.0,202340.528455,20520.913846,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
164535,content_a9322b74ca7cb1bb,client_23a62021009f63c4,139885.0,98702.991667,10010.184167,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
25405,content_36e53e9c707674fc,client_23a62021009f63c4,784715.0,81660.728571,8950.787857,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
24900,content_e8a52cf3d5988c07,client_23a62021009f63c4,1285914.0,55178.128571,6803.726857,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
157149,content_39457d17e716086c,client_e5c2aa26a8598242,285818.0,60743.098485,6360.127848,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
266957,content_661a7734f691bef5,client_23a62021009f63c4,624732.0,54211.272031,6045.859203,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
245384,content_eadb33b5df496f4a,client_e547b89c05043229,2902616.0,25991.498084,5501.765808,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
354859,content_82e35c4845e6c391,client_20259bd6705d81d4,303874.0,51580.810606,5461.955061,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
225200,content_0aaa197051f58d6f,client_fef1a8f436438636,472848.0,45645.310734,5037.379073,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
237924,content_df47d1b976106de4,client_23a62021009f63c4,632471.0,43242.278571,4956.698857,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
356058,content_aa412de014b806a0,client_20259bd6705d81d4,163716.0,47818.810606,4945.597061,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
23067,content_ba462518dad435fc,client_fef1a8f436438636,481998.0,44160.032143,4898.001214,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
142817,content_5941f92782343e72,client_20259bd6705d81d4,185513.0,46784.636364,4863.976636,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
355801,content_0b7e2cd65fadec6f,client_20259bd6705d81d4,193662.0,45513.613636,4745.023364,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
238277,content_3df3f32f3fd58dea,client_23a62021009f63c4,523162.0,41702.846429,4693.446643,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
142897,content_a11bd5663919f057,client_20259bd6705d81d4,145911.0,44048.075758,4550.718576,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
24879,content_bdf60c86117079be,client_23a62021009f63c4,356584.0,41154.385714,4472.022571,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
11828,content_7a0a59b4cb181ab9,client_fef1a8f436438636,401188.0,37617.572238,4162.945224,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
31924,content_ba98b9ba325cb149,client_e547b89c05043229,237716.0,39089.429119,4146.658912,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW
31986,content_9b76202a02885037,client_e547b89c05043229,275036.0,38408.984674,4115.934467,HIGH_VOLUME_LOW_POSITION,SEO_REVIEW

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

In [ ]:
top20 = queue.head(20).copy()

top20["confidence"] = "Medium"

top20["why"] = (
    "High impressions combined with poor average position."
)

top20["what_would_make_it_wrong"] = (
    "Traffic may be seasonal or recent ranking changes may already be improving."
)

top20[
[
"content_hash_id",
"action",
"reason_code",
"confidence",
"why",
"what_would_make_it_wrong"
]
]

,content_hash_id,action,reason_code,confidence,why,what_would_make_it_wrong
160364,content_c60628276389acbb,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
164535,content_a9322b74ca7cb1bb,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
25405,content_36e53e9c707674fc,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
24900,content_e8a52cf3d5988c07,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
157149,content_39457d17e716086c,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
266957,content_661a7734f691bef5,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
245384,content_eadb33b5df496f4a,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
354859,content_82e35c4845e6c391,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
225200,content_0aaa197051f58d6f,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
237924,content_df47d1b976106de4,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
356058,content_aa412de014b806a0,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
23067,content_ba462518dad435fc,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
142817,content_5941f92782343e72,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
355801,content_0b7e2cd65fadec6f,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
238277,content_3df3f32f3fd58dea,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
142897,content_a11bd5663919f057,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
24879,content_bdf60c86117079be,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
11828,content_7a0a59b4cb181ab9,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
31924,content_ba98b9ba325cb149,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...
31986,content_9b76202a02885037,SEO_REVIEW,HIGH_VOLUME_LOW_POSITION,Medium,High impressions combined with poor average po...,Traffic may be seasonal or recent ranking chan...

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

## Weak Picks + Leakage Check

Some pages may rank highly because of temporary traffic spikes rather than true optimization opportunities.

The rule uses only historical search performance and does not use any future information or label-derived variables.

No future windows or product flags were used, so no data leakage is present.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.